# database connection information
url: jdbc:sqlserver://demo-db1-win.liquibase.net:1433;databaseName=npt_dev;encrypt=false
username: DATICAL_USER
password: DATICAL_USER_PW
changelogFile: src/master_changelog.xml

# The default author name given in each changeset
liquibase.command.author: amalik

# Objects to exclude ...
liquibase.command.excludeObjects: schema:sys,information_schema

# Overwrite existing output/changelog file
liquibase.command.overwriteOutputFile: true

# Specifies database schemas you want to include. Comma separate multiple schemas
liquibase.command.schemas: adeel1,dbo

# If true, the schema will be included in generated changesets.
liquibase.command.includeSchema: yes

